services:
  db:
    container_name: db
    image: mysql
    restart: on-failure
    environment:
      MYSQL_DATABASE: resume
      MYSQL_ROOT_HOST: '%'
      MYSQL_ROOT_PASSWORD: 1234
      TZ: 'Asia/Seoul'
    ports:
      - "3306:3306"
    volumes:
      - ./src/main/resources/dummy-data.sql:/docker-entrypoint-initdb.d/dummy-data.sql
      - ./mysql-config/my.cnf:/etc/mysql/conf.d/my.cnf  # 사용자 정의 설정 파일
    tty: true

volumes:
  mysql_data: