name: Gihub Actions

# main 브랜치에 푸쉬될 때 아래 job 실행
on:
  push:
    branches:
      - main

# 하나의 Workflow는 1개 이상의 Job
# 여러 Job은 기본적으로 병렬 수행
jobs:
  # Job 식별 id
  My-Deploy-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: gradlew 실행 권한 추가
        run: chmod +x ./gradlew

      - name: 테스트 및 빌드
        run: ./gradlew clean build -x test

      - name: 식별하기 좋게 빌드 파일명 변경
        run: mv ./build/libs/*SNAPSHOT.jar ./gwangho-success.jar

      - name: SCP로 EC2에 빌드된 파일 전송
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          source: gwangho-success.jar
          target: /home/ubuntu/ho-resume/tobe

      - name : EC2 SSH 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            rm -rf /home/ubuntu/ho-resume/current
            mkdir /home/ubuntu/ho-resume/current
            mv /home/ubuntu/ho-resume/tobe/gwangho-success.jar /home/ubuntu/ho-resume/current/gwangho-success.jar
            cd /home/ubuntu/ho-resume/current
            sudo fuser -k -n tcp 8080 || true
            nohup java -jar gwangho-success.jar > ./output.log 2>&1 &
            rm -rf /home/ubuntu/ho-resume/tobe