name: Gihub Actions

# main 브랜치에 푸쉬될 때 아래 job 실행
on:
  push:
    branches:
      - main

# 하나의 Workflow는 1개 이상의 Job
# 여러 Job은 기본적으로 병렬 수행
jobs:
  # Job 식별 id
  My-Deploy-Job:
    runs-on: ubuntu-latest
    steps:
      - name: Github Repository 파일 불러오기
        uses: actions/checkout@v4

      - name: JDK 17 설치
        uses: actions/setup-java@v4
        with:
          distribution: temurin
          java-version: 17

      - name: gradlew 실행 권한 추가
        run: chmod +x ./gradlew

      - name: 테스트 및 빌드
        run: ./gradlew clean build -x test

      - name: AWS Resource에 접근할 수 있게 AWS credentials 설정
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: ap-northeast-2
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}

      - name: ECR 로그인
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Docker 이미지 생성
        run: docker build -t ho-resume .

      - name: Docker 이미지에 Tag 붙이기
        run: docker tag ho-resume ${{ steps.login-ecr.outputs.registry }}/commerce-server-ecr:latest

      - name: ECR에 Docker 이미지 Push하기
        run: docker push ${{ steps.login-ecr.outputs.registry }}/commerce-server-ecr:latest

      - name: SSH로 EC2에 접속하기
        uses: appleboy/ssh-action@v1.0.3
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_PRIVATE_KEY }}
          script_stop: true
          script: |
            docker stop ho-resume || true
            docker rm ho-resume || true
            docker pull ${{ steps.login-ecr.outputs.registry }}/commerce-server-ecr:latest
            docker run -d --name ho-resume -p 8080:8080 ${{ steps.login-ecr.outputs.registry }}/commerce-server-ecr:latest